# Generated by Django 3.1.7 on 2021-05-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acccounts', '0002_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
